### ISSUE TITLE
REGARDING FORWARDING

### ISSUE THREAD

**Issue by Lakka19** [konichar/parsesig#4]
Hi,
My forex signals provider provide signals on image so i want to convert image to txt and forward so can i do that with your software ?

**Comment by rwelson** [comment]
use OCR Feature to convert image to text before posting.

**Comment by richardokonicha** [comment]
hello, well this is very possible but not with the example piece, what you would most likely need is firstly some kind of image to text like python module [pytesseract · PyPI](https://pypi.org/project/pytesseract/) its an OCR tool this extracts your signals then you can forward it to your destination. 
but yes it is possible to implement that functionality on this project.
